// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APProjS.Migrations
{
    [DbContext(typeof(ToDoClass))]
    partial class ToDoClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TaskdeadLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taskname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TaskperentCompeleted")
                        .HasColumnType("REAL");

                    b.Property<int>("Tasktimeneeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MyTodo");
                });
#pragma warning restore 612, 618
        }
    }
}
